user  root;
worker_processes  1;

events {
}

http {
    server {
        listen       80;
        server_name  ваш_ip;

        location / {
            proxy_pass http://backfrontend:8000/;
        }
    }
}
